# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "centos.example.com"
    centos.vm.network "private_network", ip: "172.20.0.2"
    centos.vm.provider "virtualbox" do |v|
      v.name = "centos"
      v.memory = 1024
      v.cpus = 1
    end
    centos.vm.provision "shell", path: "bootstrap_centos.sh"
  end
end
